package com.google.adk.kt.examples.agents.llmagent

import com.google.adk.kt.agents.Instruction
import com.google.adk.kt.agents.LlmAgent
import com.google.adk.kt.annotations.Param
import com.google.adk.kt.annotations.Tool
import com.google.adk.kt.models.Gemini
import com.google.adk.kt.runners.InMemoryRunner
import com.google.adk.kt.sessions.InMemorySessionService
import com.google.adk.kt.types.Content
import com.google.adk.kt.types.GenerateContentConfig
import com.google.adk.kt.types.Part
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.runBlocking

// --8<-- [start:tool_definition]
class CapitalService {
    @Tool(description = "Retrieves the capital city for a given country.")
    fun getCapitalCity(
        @Param("The country to get capital for.") country: String,
    ): String {
        val capitals = mapOf("france" to "Paris", "japan" to "Tokyo", "canada" to "Ottawa")
        return capitals[country.lowercase()] ?: "Sorry, I don't know the capital of $country."
    }
}
// --8<-- [end:tool_definition]

fun main() =
    runBlocking {
        val capitalService = CapitalService()

        // --8<-- [start:identity]
        val capitalAgent =
            LlmAgent(
                name = "capital_agent",
                model = Gemini(name = "gemini-flash-latest"),
                description = "Answers user questions about the capital city of a given country.",
            )
        // --8<-- [end:identity]

        // --8<-- [start:instruction]
        val instructedAgent =
            LlmAgent(
                name = "capital_agent",
                model = Gemini(name = "gemini-flash-latest"),
                instruction =
                    Instruction(
                        """
                        You are an agent that provides the capital city of a country.
                        When a user asks for the capital of a country:
                        1. Identify the country name from the user's query.
                        2. Use the `getCapitalCity` tool to find the capital.
                        3. Respond clearly to the user, stating the capital city.
                        Example Query: "What's the capital of {country}?"
                        Example Response: "The capital of France is Paris."
                        """.trimIndent(),
                    ),
            )
        // --8<-- [end:instruction]

        // --8<-- [start:tool_usage]
        // Note: generatedTools() is generated by KSP for classes containing @Tool annotated functions.
        // In a real project, you would need to set up the ADK KSP processor.
        // val agentWithTools = LlmAgent(
        //     name = "capital_agent",
        //     model = Gemini(name = "gemini-flash-latest"),
        //     tools = capitalService.generatedTools()
        // )
        // --8<-- [end:tool_usage]

        // --8<-- [start:gen_config]
        val agentWithConfig =
            LlmAgent(
                name = "capital_agent",
                model = Gemini(name = "gemini-flash-latest"),
                generateContentConfig =
                    GenerateContentConfig(
                        temperature = 0.2f,
                        maxOutputTokens = 250,
                    ),
            )
        // --8<-- [end:gen_config]

        // --8<-- [start:full_example]
        val finalAgent =
            LlmAgent(
                name = "capital_agent",
                model = Gemini(name = "gemini-flash-latest"),
                description = "Answers user questions about the capital city of a given country.",
                instruction =
                    Instruction(
                        "You are an agent that provides the capital city of a country...",
                    ),
                // tools = capitalService.generatedTools() // Assuming tools are added
            )

        val sessionService = InMemorySessionService()
        val runner = InMemoryRunner(finalAgent, "capital_app", sessionService)

        val userMessage = Content(parts = listOf(Part(text = "What is the capital of France?")))

        // Use runAsync to get a Flow of events
        runner.runAsync(
            userId = "user123",
            sessionId = "session456",
            newMessage = userMessage,
        ).collect {
                event ->
            if (event.isFinalResponse) {
                val finalResponse = event.content?.parts?.firstOrNull()?.text
                println(finalResponse)
            }
        }
        // --8<-- [end:full_example]
    }
